version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  midas-database:
    image: mysql
    container_name: midas-database
    environment:
      MYSQL_ROOT_PASSWORD: Student2-
      MYSQL_DATABASE: students
      MYSQL_USER: sammy
      MYSQL_PASSWORD: Student2-
    ports:
      - "3306:3306"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - midas-database

